#!/bin/sh

umask 002

cd $(dirname "$0")

. ./params.sh

comment="$QUERY_STRING"
len=$(echo -n "$comment" | wc -c)

if [ -e threads ]
then
	no=$(cat threads)
else
	no=0
fi
no=$(($no + 1))

stamp=$(date +%s)
post=$no

if [ "$len" -gt "$MAX_TITLELEN" ]
then
	pherror 'Thread creation failed.'
	phline
	phinfo "Title too long ($len/$MAX_TITLELEN)"
	phitem 1 'Return' "$CHAN_ROOT"
	exit 1
fi

if [ "$MAX_THREADS" -lt 1 ]
then
	pherror 'New threads are disabled on this board.'
	phitem 1 Return "$CHAN_ROOT"
	exit 1
fi

if [ "$comment" = "" ]
then
	pherror 'Thread creation failed: You must include a title'
	phitem 1 Return "$CHAN_ROOT"
	exit 1
fi

coolstorybro=$(sh cooldown.sh thread)
if ! $coolstorybro
then
	pherror "Thread creation failed"
	phline
	phinfo "Please wait $POST_LIMIT seconds before creating a new thread."
	phitem 1 "Return" "$CHAN_ROOT"
	exit 1
fi

mkdir ../$post
mkdir ../$post/cgi-bin

if [ -e ../$post ]
then
	echo "$comment" > ../$post/gophertag

	ln template_gophermap ../$post/gophermap
	ln template_post ../$post/cgi-bin/post
	ln template_postlink ../$post/cgi-bin/postlink
	ln template_postfile ../$post/cgi-bin/postfile
	ln template_postsplr ../$post/cgi-bin/postsplr
	ln template_postfileb64 ../$post/cgi-bin/postfileb64
	ln template_postb64 ../$post/cgi-bin/postb64

	touch ../$post/postcache
	echo $stamp > ../$post/cgi-bin/stamp

	phinfo 'Thread created successfully!'
	phitem 1 'View thread' "$CHAN_ROOT/$post"

	echo $no > threads
	
	nthreads=$(find ../[0-9]* -maxdepth 0 -type d 2>/dev/null | wc -l)

    while [ $nthreads -gt $MAX_THREADS ]
    do
        nthreads=$(($nthreads-1))  
        thread=$(ls -dt $(find ../[0-9]* -maxdepth 0 -type d) | tail -1)
        if [ "$ENABLE_ARCHIVE" != n ]
        then
            sh archive.sh $thread
                
            if [ -f $thread ]
            then
                pherror 'Failed to archive thread!'
                phitem 1 Return "$CHAN_ROOT"
                continue
            fi
        else
            rm -r $thread

            if [ -f $thread ]
            then
                pherror 'Failed to remove thread!'
                phitem 1 Return "$CHAN_ROOT"
                continue
            fi
        fi
    done

	sh updatethreadcache.sh > ../threadcache
else
	pherror 'Could not create thread.'
	phitem 1 Return "$CHAN_ROOT"
	exit 1
fi
